# Generated by Django 4.1.1 on 2022-10-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_rest_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal_Information',
            new_name='PersonalInformation',
        ),
    ]
