# Generated by Django 4.1.1 on 2022-10-04 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_rest_django', '0002_rename_personal_information_personalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=100)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='basic_rest_django.personalinformation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
