# Generated by Django 4.1.1 on 2022-10-04 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_rest_django', '0003_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='personal',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='basic_rest_django.address'),
            preserve_default=False,
        ),
    ]
