# Generated by Django 4.1.1 on 2022-10-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_rest_django', '0004_rename_address_address_city_remove_address_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_address', to='basic_rest_django.address'),
        ),
    ]
