# Generated by Django 4.1 on 2022-10-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_rest_django', '0007_remove_personalinformation_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
