# Generated by Django 4.1 on 2022-10-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_rest_django', '0011_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
