# Generated by Django 4.1 on 2022-10-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_rest_django', '0012_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
    ]
