# Generated by Django 4.1 on 2022-10-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_rest_django', '0013_delete_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
